### ISSUE TITLE
Crash podczas odpalania apki

### ISSUE THREAD

**Issue by wvffle** [pb-iot/simulator#22]
```
greenhouse-manager-sim-1         | 
greenhouse-manager-sim-1         | 
greenhouse-manager-sim-1         |   .   ____          _            __ _ _
greenhouse-manager-sim-1         |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
greenhouse-manager-sim-1         | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
greenhouse-manager-sim-1         |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
greenhouse-manager-sim-1         |   '  |____| .__|_| |_|_| |_\__, | / / / /
greenhouse-manager-sim-1         |  =========|_|==============|___/=/_/_/_/
greenhouse-manager-sim-1         |  :: Spring Boot ::                (v3.1.4)
greenhouse-manager-sim-1         | 
greenhouse-manager-sim-1         | 
greenhouse-manager-sim-1         | 2024-01-17T13:02:20.946Z  INFO 7 --- [           main] c.e.simulator.SimulatorApplication       : Starting SimulatorApplication v0.0.1-SNAPSHOT using Java 21.0.1 with PID 7 (/app/sim.jar started by root in /app)
greenhouse-manager-sim-1         | 2024-01-17T13:02:20.949Z  INFO 7 --- [           main] c.e.simulator.SimulatorApplication       : No active profile set, falling back to 1 default profile: "default"
greenhouse-manager-sim-1         | 2024-01-17T13:02:22.625Z  INFO 7 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
greenhouse-manager-sim-1         | 2024-01-17T13:02:22.638Z  INFO 7 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
greenhouse-manager-sim-1         | 2024-01-17T13:02:22.638Z  INFO 7 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.13]
greenhouse-manager-sim-1         | 2024-01-17T13:02:22.741Z  INFO 7 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
greenhouse-manager-sim-1         | 2024-01-17T13:02:22.743Z  INFO 7 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1719 ms
greenhouse-manager-sim-1         | 2024-01-17T13:02:24.121Z  INFO 7 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
greenhouse-manager-sim-1         | 2024-01-17T13:02:24.224Z  INFO 7 --- [           main] c.e.simulator.SimulatorApplication       : Started SimulatorApplication in 3.91 seconds (process running for 4.553)
greenhouse-manager-sim-1         | 2024-01-17T13:02:24.948Z  INFO 7 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 
greenhouse-manager-sim-1         | 
greenhouse-manager-sim-1         | 
greenhouse-manager-sim-1         | Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
greenhouse-manager-sim-1         | 2024-01-17T13:02:24.973Z ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application run failed
greenhouse-manager-sim-1         | 
greenhouse-manager-sim-1         | 
greenhouse-manager-sim-1         | java.lang.IllegalStateException: Failed to execute CommandLineRunner
greenhouse-manager-sim-1         | 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:777) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1         | 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:758) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1         | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1         | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1         | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1         | 	at com.example.simulator.SimulatorApplication.main(SimulatorApplication.java:16) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
greenhouse-manager-sim-1         | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
greenhouse-manager-sim-1         | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[sim.jar:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[sim.jar:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[sim.jar:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[sim.jar:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | Caused by: java.lang.NullPointerException: Cannot invoke "com.example.simulator.utils.forecast.data.CurrentWeather.getHumidity2m()" because "currentWeather" is null
greenhouse-manager-sim-1         | 	at com.example.simulator.greenhouse.sensors.humiditySensor.HumiditySensor.<init>(HumiditySensor.java:15) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at com.example.simulator.greenhouse.simulators.HumiditySimulation.<init>(HumiditySimulation.java:19) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at com.example.simulator.greenhouse.simulators.SimulationType.getSimulable(SimulationType.java:21) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at com.example.simulator.greenhouse.Greenhouse.addSimulation(Greenhouse.java:38) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at com.example.simulator.service.GreenhouseService.addSimulation(GreenhouseService.java:15) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at com.example.simulator.SimulatorApplication.lambda$loadData$0(SimulatorApplication.java:23) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1         | 	... 11 common frames omitted
greenhouse-manager-sim-1         | 
greenhouse-manager-sim-1         | 
greenhouse-manager-sim-1 exited with code 1
```

**Comment by wvffle** [comment]
@ondreo moglbys zerknac?

**Comment by ondreo** [comment]
Ok, sprawdzę u siebie jutro wieczorem

**Comment by ondreo** [comment]
Sprawdziłem właśnie - ja nie mam takiego problemu. Z tego co widzę po logach, to problem występuje na serwerze, na którym była postawiona aplikacja (https://gm-api.wvffle.net/), zgadza się?

Wygląda na to, że obiekt `currentWeather` jest nullem, ponieważ aplikacja https://api.open-meteo.com/, z której bierzemy dane dotyczące pogody w danej lokalizacji nie zwraca tego obiektu - prawdopodobnie blokuje ruch. Może to była jednorazowa kwestia, a może na serwerze z aplikacją jest jakiś VPN zapięty? To może blokować ruch do tego typu darmowych api.

**Comment by wvffle** [comment]
>  Z tego co widzę po logach, to problem występuje na serwerze, na którym była postawiona aplikacja (https://gm-api.wvffle.net/), zgadza się?

Tak.

> Może to była jednorazowa kwestia

Blad caly czas wystepuje, aktualny log:
```
greenhouse-manager-sim-1  | 
greenhouse-manager-sim-1  |   .   ____          _            __ _ _
greenhouse-manager-sim-1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
greenhouse-manager-sim-1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
greenhouse-manager-sim-1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
greenhouse-manager-sim-1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
greenhouse-manager-sim-1  |  =========|_|==============|___/=/_/_/_/
greenhouse-manager-sim-1  | 
greenhouse-manager-sim-1  |  :: Spring Boot ::                (v3.1.4)
greenhouse-manager-sim-1  | 
greenhouse-manager-sim-1  | 
greenhouse-manager-sim-1  | 2024-01-19T22:05:48.409Z  INFO 7 --- [           main] c.e.simulator.SimulatorApplication       : Starting SimulatorApplication v0.0.1-SNAPSHOT using Java 21.0.1 with PID 7 (/app/sim.jar started by root in /app)
greenhouse-manager-sim-1  | 2024-01-19T22:05:48.413Z  INFO 7 --- [           main] c.e.simulator.SimulatorApplication       : No active profile set, falling back to 1 default profile: "default"
greenhouse-manager-sim-1  | 2024-01-19T22:05:50.185Z  INFO 7 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
greenhouse-manager-sim-1  | 2024-01-19T22:05:50.213Z  INFO 7 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
greenhouse-manager-sim-1  | 2024-01-19T22:05:50.214Z  INFO 7 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.13]
greenhouse-manager-sim-1  | 2024-01-19T22:05:50.355Z  INFO 7 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
greenhouse-manager-sim-1  | 2024-01-19T22:05:50.357Z  INFO 7 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1856 ms
greenhouse-manager-sim-1  | 2024-01-19T22:05:51.906Z  INFO 7 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
greenhouse-manager-sim-1  | 2024-01-19T22:05:51.946Z  INFO 7 --- [           main] c.e.simulator.SimulatorApplication       : Started SimulatorApplication in 4.452 seconds (process running for 5.535)
greenhouse-manager-sim-1  | 2024-01-19T22:05:52.907Z  INFO 7 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 
greenhouse-manager-sim-1  | 
greenhouse-manager-sim-1  | Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
greenhouse-manager-sim-1  | 
greenhouse-manager-sim-1  | 2024-01-19T22:05:52.945Z ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application run failed
greenhouse-manager-sim-1  | 
greenhouse-manager-sim-1  | java.lang.IllegalStateException: Failed to execute CommandLineRunner
greenhouse-manager-sim-1  | 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:777) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1  | 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:758) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1  | 	at com.example.simulator.SimulatorApplication.main(SimulatorApplication.java:16) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1  | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
greenhouse-manager-sim-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
greenhouse-manager-sim-1  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[sim.jar:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[sim.jar:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[sim.jar:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1  | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[sim.jar:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1  | Caused by: java.lang.NullPointerException: Cannot invoke "com.example.simulator.utils.forecast.data.CurrentWeather.getHumidity2m()" because "currentWeather" is null
greenhouse-manager-sim-1  | 	at com.example.simulator.greenhouse.sensors.humiditySensor.HumiditySensor.<init>(HumiditySensor.java:15) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1  | 	at com.example.simulator.greenhouse.simulators.HumiditySimulation.<init>(HumiditySimulation.java:19) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1  | 	at com.example.simulator.greenhouse.simulators.SimulationType.getSimulable(SimulationType.java:21) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1  | 	at com.example.simulator.greenhouse.Greenhouse.addSimulation(Greenhouse.java:38) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1  | 	at com.example.simulator.service.GreenhouseService.addSimulation(GreenhouseService.java:15) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1  | 	at com.example.simulator.SimulatorApplication.lambda$loadData$0(SimulatorApplication.java:23) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1  | 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1  | 	... 11 common frames omitted
```

> może na serwerze z aplikacją jest jakiś VPN zapięty

Serwer jest w 100% kontrolowany przezemnie, nie ma tam VPNa, a firewall nie wycina zadnego ruchu. 

```sh
$ curl https://api.open-meteo.com/v1/forecast\?latitude\=53.1221\&longitude\=23.1443\&current\=temperature_2m,apparent_temperature,is_day 
```

zwraca pieknie

```json
{"latitude":53.125,"longitude":23.125,"generationtime_ms":0.06103515625,"utc_offset_seconds":0,"timezone":"GMT","timezone_abbreviation":"GMT","elevation":149.0,"current_units":{"time":"iso8601","interval":"seconds","temperature_2m":"°C","apparent_temperature":"°C","is_day":""},"current":{"time":"2024-01-19T22:00","interval":900,"temperature_2m":-3.8,"apparent_temperature":-8.1,"is_day":0}}
```

**Comment by ondreo** [comment]
Odpaliłem u siebie lokalnie aplikację jako kontener - zbudowałem ją przez plik `Dockerfile` będący w głównym folderze repozytorium (https://github.com/pb-iot/simulator/), czyli:
```
FROM maven:3.9-sapmachine-21 as build

WORKDIR /app

COPY ./src ./src
COPY ./pom.xml ./pom.xml

RUN mvn -f pom.xml clean package

FROM sapmachine:21-jdk-ubuntu

WORKDIR /app

COPY --from=build /app/target/*.jar sim.jar

EXPOSE 8080
CMD java -jar sim.jar
```

Obraz zbudowałem poleceniem: `docker build -t sim:latest .`.

Następnie stworzyłem taki plik `docker-compose.yml`:
```
version: '3'

services:
  sim:
    image: sim:latest
    restart: always
    ports:
      - '8080:8080'
```

Następnie uruchomiłem poleceniem `docker-compose up -d`.

Aplikacja uruchomiła się normalnie i działa.

Aplikacja działa również jak w pliku `docker-compose.yml` zamieniłem obraz `sim:latest` na `ghcr.io/pb-iot/greenhouse-manager-sim:latest` i jeszcze raz włączyłem aplikację.

Nie wiem zatem z czego może wynikać problem ://

@wvffle może mógłbyś sprawdzić czy z poziomu kontenera (np. frontendowego, skoro kontener symulatora nie działa) da się to samo polecenie `curl`, co wysłałeś, z powodzeniem wykonać? Może da się z poziomu serwera, a ruch z kontenera jest jakimś cudem zablokowany?

**Comment by ondreo** [comment]
I jeszcze pytanko - na wersji z którego dnia działa obecnie https://gm-sim.wvffle.net/?

**Comment by ondreo** [comment]
Jeszcze jedno: co oznacza fragment:
```
ALLOWED_HOSTS: "gm-sim.wvffle.net"
```
w pliku https://github.com/pb-iot/deployment/blob/master/docker-compose.yml?

**Comment by wvffle** [comment]
> @wvffle może mógłbyś sprawdzić czy z poziomu kontenera (np. frontendowego, skoro kontener symulatora nie działa) da się to samo polecenie curl, co wysłałeś, z powodzeniem wykonać?

Na spokojnie moge wykonac curla z waszego kontenera. Kazdy kontener dostaje u mnie wlasny publiczny IPv6 wiec nie dziwota, ze z poziomu kontenera nie dziala. Dodajcie obsluge bledow  i moze pytajcie sie rzadziej po prostu ;)

```json
{"reason":"Daily API request limit exceeded. Please try again tomorrow.","error":true}
``` 

> I jeszcze pytanko - na wersji z którego dnia działa obecnie https://gm-sim.wvffle.net/?

Zawsze najnowsza z glownego brancha

> Jeszcze jedno: co oznacza fragment:
>> ALLOWED_HOSTS: "gm-sim.wvffle.net"

chamsko skopiowany env var przy tworzeniu docker-compose. Jak nie uzywacie w apce to nic wam nie zmienia.


@ondreo

**Comment by ondreo** [comment]
Ok, dzięki za odpowiedź

**Comment by wvffle** [comment]
mozecie to obsluzyc?

**Comment by ondreo** [comment]
👍

**Comment by ondreo** [comment]
Wersja z poprawką jest już na masterze - jeśli dalej by coś nie grało, to daj znać @wvffle. Póki co zamykam zadanie.

**Comment by wvffle** [comment]
@ondreo błąd nadal występuje, nawet po aktualizacji:
```
greenhouse-manager-sim-1         | java.lang.IllegalStateException: Failed to execute CommandLineRunner
greenhouse-manager-sim-1         | 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:777) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1         | 	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:758) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1         | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1         | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1         | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1         | 	at com.example.simulator.SimulatorApplication.main(SimulatorApplication.java:16) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
greenhouse-manager-sim-1         | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
greenhouse-manager-sim-1         | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[sim.jar:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95) ~[sim.jar:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[sim.jar:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[sim.jar:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | Caused by: java.lang.NullPointerException: Cannot invoke "com.example.simulator.utils.forecast.data.CurrentWeather.getHumidity2m()" because "currentWeather" is null
greenhouse-manager-sim-1         | 	at com.example.simulator.greenhouse.sensors.humiditySensor.HumiditySensor.<init>(HumiditySensor.java:15) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at com.example.simulator.greenhouse.simulators.HumiditySimulation.<init>(HumiditySimulation.java:19) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at com.example.simulator.greenhouse.simulators.SimulationType.getSimulable(SimulationType.java:21) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at com.example.simulator.greenhouse.Greenhouse.addSimulation(Greenhouse.java:38) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at com.example.simulator.service.GreenhouseService.addSimulation(GreenhouseService.java:15) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at com.example.simulator.SimulatorApplication.lambda$loadData$0(SimulatorApplication.java:23) ~[classes!/:0.0.1-SNAPSHOT]
greenhouse-manager-sim-1         | 	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:774) ~[spring-boot-3.1.4.jar!/:3.1.4]
greenhouse-manager-sim-1         | 	... 11 common frames omitted
greenhouse-manager-sim-1         | 
```

Poki co wylaczylem caly deploy, sprawdze wieczorem czy juz moge wlaczyc bezproblemowo

**Comment by ondreo** [comment]
Według oficjalnej strony wystawci API (https://open-meteo.com/en/pricing) jest info:
![image](https://github.com/pb-iot/simulator/assets/65464616/961eabaa-dd15-436e-bdeb-64e41d28d1c9)

10 tysięcy requestów dziennie nie wykonujemy przynajmniej przy nowych ustawieniach. 10 tysięcy requestów dziennie oznacza około 6.94444444 requestów na minutę - stare ustawienia mogły spokojnie ten limit przekraczać (teraz mamy 1 request co minutę, więc nie powinno przekraczać) - poczekajmy z tym może do jutra - nie wiem o której się zeruje licznik requestów, ale 24 godziny wyłączonej aplikacji symulatora powinno umożliwić zresetowanie licznika do zera.

**Comment by ondreo** [comment]
@wvffle czy sprawdzałeś już może, czy apka śmiga? Widzę, że pod adresem https://gm-sim.wvffle.net/swagger-ui/index.html swagger działa, więc chyba włączyłeś z powrotem deployment, tak?

**Comment by wvffle** [comment]
@ondreo, tak. Włączyłem o 17 dziś, nie widać by były jakieś błędy. Dzięki za reakcję!
